<a href="https://colab.research.google.com/github/icervecon/Dividend-Design-UCITS-Funds/blob/main/Paper_Dividend_Design_UCITS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dividend Policies as Product Design: Evidence from UCITS Funds and the Role of Asset Management Firms

In [75]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [76]:
file_path = "ucits_dividend_data.xlsx"
df = pd.read_excel(file_path)

In [77]:
df['dividend'] = df['has_paid_dividends_i']
df['CL4_yes'] = (df['CL4'] == 'Yes').astype(int)

Table 1- Descriptive Statistics- Panel A- Full Sample

In [78]:
vars_desc = [
    'dividend',
    'retail_eligible_i',
    'CL4_yes',
    'log_tna',
    'fund_age_years',
    'is_equity',
    'is_fixed_income'
]

desc = df[vars_desc].describe().T

desc = desc[['mean', 'std', 'min', 'max']]
desc

                        mean       std       min        max
dividend            0.310902  0.462905  0.000000   1.000000
retail_eligible_i   0.862805  0.344141  0.000000   1.000000
CL4_yes             0.421005  0.493765  0.000000   1.000000
log_tna             3.929630  2.090602  0.000089  11.677366
fund_age_years     14.159420  8.492873  0.005476  53.188227
is_equity           0.348268  0.476465  0.000000   1.000000
is_fixed_income     0.299111  0.457910  0.000000   1.000000

Table 1- Descriptive Statistics- Panel B- By Retail Eligibility

In [79]:
vars_desc = [
    'dividend',
    'CL4_yes',
    'log_tna',
    'fund_age_years',
    'is_equity',
    'is_fixed_income'
]

grouped = df.groupby('retail_eligible_i')[vars_desc].mean().T

grouped.columns = ['Non-Retail', 'Retail']

grouped['Difference'] = grouped['Retail'] - grouped['Non-Retail']

grouped

                 Non-Retail     Retail  Difference
dividend           0.144444   0.409894    0.265450
CL4_yes            0.977778   0.985866    0.008088
log_tna            4.017750   4.184931    0.167181
fund_age_years     9.283180  10.419109    1.135929
is_equity          0.385185   0.383392   -0.001793
is_fixed_income    0.259259   0.314488    0.055228

Table 2. Accessibility and Dividend Policies (Baseline)

In [80]:
import statsmodels.formula.api as smf

# Ensure there are no issues with NaNs in the group
df_model = df.dropna(subset=[
    'dividend',
    'retail_eligible_i',
    'CL4_yes',
    'Management_Group'
]).copy()

df_model['Management_Group_clean'] = df_model['Management_Group'].astype(str)

# Model with clustering
model = smf.ols(
    formula="dividend ~ retail_eligible_i + CL4_yes",
    data=df_model
).fit(
    cov_type='cluster',
    cov_kwds={'groups': df_model['Management_Group_clean']}
)

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               dividend   R-squared:                       0.038
Model:                            OLS   Adj. R-squared:                  0.037
Method:                 Least Squares   F-statistic:                     17.72
Date:                Mon, 04 May 2026   Prob (F-statistic):           6.25e-08
Time:                        06:52:05   Log-Likelihood:                -1321.5
No. Observations:                1963   AIC:                             2649.
Df Residuals:                    1960   BIC:                             2666.
Df Model:                           2
Covariance Type:              cluster
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept            -0.0568      0.093     -0.611      0.541      -0.239       0.125
retail_eligible_i     0.2635      0.045      5.826      0.000       0.175       0.352
CL4_yes               0.2058      0.094      2.187      0.029       0.021       0.390
==============================================================================
Omnibus:                     9432.993   Durbin-Watson:                   1.482
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              295.345
Skew:                           0.459   Prob(JB):                     7.36e-65
Kurtosis:                       1.336   Cond. No.                         20.2
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

Table 3. Fund Characteristics and Dividend Policies.

In [81]:
import statsmodels.formula.api as smf

df_model = df.dropna(subset=[
    'dividend',
    'retail_eligible_i',
    'CL4_yes',
    'log_tna',
    'fund_age_years',
    'is_equity',
    'is_fixed_income',
    'Management_Group'
]).copy()

df_model['Management_Group_clean'] = df_model['Management_Group'].astype(str)

model_controls = smf.ols(
    formula="""
    dividend ~ retail_eligible_i + CL4_yes
    + log_tna + fund_age_years
    + is_equity + is_fixed_income
    """,
    data=df_model
).fit(
    cov_type='cluster',
    cov_kwds={'groups': df_model['Management_Group_clean']}
)

print(model_controls.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               dividend   R-squared:                       0.106
Model:                            OLS   Adj. R-squared:                  0.103
Method:                 Least Squares   F-statistic:                     14.72
Date:                Mon, 04 May 2026   Prob (F-statistic):           2.03e-14
Time:                        06:52:05   Log-Likelihood:                -1223.2
No. Observations:                1930   AIC:                             2460.
Df Residuals:                    1923   BIC:                             2499.
Df Model:                           6
Covariance Type:              cluster
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept            -0.2605      0.110     -2.359      0.018      -0.477      -0.044
retail_eligible_i     0.2345      0.044      5.304      0.000       0.148       0.321
CL4_yes               0.1526      0.093      1.636      0.102      -0.030       0.335
log_tna               0.0186      0.014      1.370      0.171      -0.008       0.045
fund_age_years        0.0171      0.003      5.862      0.000       0.011       0.023
is_equity             0.0347      0.038      0.913      0.361      -0.040       0.109
is_fixed_income       0.0388      0.042      0.918      0.358      -0.044       0.122
==============================================================================
Omnibus:                    69813.093   Durbin-Watson:                   1.603
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              215.353
Skew:                           0.458   Prob(JB):                     1.72e-47
Kurtosis:                       1.644   Cond. No.                         163.
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

Table 4. Within-Management Analysis.

In [82]:
model_fe = smf.ols(
    formula="""
    dividend ~ retail_eligible_i + CL4_yes
    + log_tna + fund_age_years
    + is_equity + is_fixed_income
    + C(Management_Group)
    """,
    data=df
).fit()

print(model_fe.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               dividend   R-squared:                       0.552
Model:                            OLS   Adj. R-squared:                  0.482
Method:                 Least Squares   F-statistic:                     7.941
Date:                Mon, 04 May 2026   Prob (F-statistic):          5.17e-162
Time:                        06:52:06   Log-Likelihood:                -556.32
No. Observations:                1930   AIC:                             1633.
Df Residuals:                    1670   BIC:                             3080.
Df Model:                         259
Covariance Type:            nonrobust
================================================================================================================
                                                   coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------
Intercept                                        0.5587      0.121      4.629      0.000       0.322       0.795
C(Management_Group)[T.3K IP MFMC]              1.38e-13   3.45e-14      3.999      0.000    7.03e-14    2.06e-13
C(Management_Group)[T.ABN AMRO]                 -0.7613      0.261     -2.922      0.004      -1.272      -0.250
C(Management_Group)[T.ACATIS]                   -0.2283      0.357     -0.640      0.522      -0.928       0.471
C(Management_Group)[T.ACOLIN]                -1.649e-14   4.03e-15     -4.092      0.000   -2.44e-14   -8.59e-15
C(Management_Group)[T.AG2R la Mondiale]       2.501e-14   3.69e-15      6.773      0.000    1.78e-14    3.22e-14
C(Management_Group)[T.AIA]                    -2.63e-14   1.69e-14     -1.552      0.121   -5.95e-14    6.94e-15
C(Management_Group)[T.AISM]                     -0.7579      0.260     -2.915      0.004      -1.268      -0.248
C(Management_Group)[T.AL Sydbank]             3.493e-14   5.96e-15      5.862      0.000    2.32e-14    4.66e-14
C(Management_Group)[T.AQA]                      -0.7429      0.358     -2.075      0.038      -1.445      -0.041
C(Management_Group)[T.AXA]                      -0.3559      0.145     -2.450      0.014      -0.641      -0.071
C(Management_Group)[T.Abanca]                -1.926e-14   5.19e-15     -3.709      0.000   -2.94e-14   -9.07e-15
C(Management_Group)[T.Aberdeen]                 -0.2971      0.098     -3.032      0.002      -0.489      -0.105
C(Management_Group)[T.Adelphi]               -7.076e-14   1.42e-14     -4.994      0.000   -9.85e-14    -4.3e-14
C(Management_Group)[T.Adenium]               -2.152e-15   5.06e-15     -0.425      0.671   -1.21e-14    7.77e-15
C(Management_Group)[T.Adepa]                    -0.9003      0.258     -3.494      0.000      -1.406      -0.395
C(Management_Group)[T.Adi]                   -6.707e-14   1.47e-14     -4.556      0.000    -9.6e-14   -3.82e-14
C(Management_Group)[T.Admio]                  -2.04e-14   5.13e-15     -3.978      0.000   -3.05e-14   -1.03e-14
C(Management_Group)[T.Advisory Research]     -2.424e-14   1.46e-14     -1.665      0.096   -5.28e-14    4.31e-15
C(Management_Group)[T.Aegon]                    -0.8358      0.115     -7.270      0.000      -1.061      -0.610
C(Management_Group)[T.Alceda]                 9.342e-15   4.15e-15      2.250      0.025     1.2e-15    1.75e-14
C(Management_Group)[T.Alessia]                4.717e-15   2.55e-15      1.851      0.064   -2.81e-16    9.71e-15
C(Management_Group)[T.Aletti Gestielle]        4.79e-15   3.52e-15      1.361      0.174   -2.11e-15    1.17e-14
C(Management_Group)[T.Alfred Berg]              -0.0161      0.258     -0.062      0.950      -0.522       0.490
C(Management_Group)[T.Allfunds]                 -0.7572      0.219     -3.458      0.001      -1.187      -0.328
C(Management_Group)[T.Alliance]                 -0.7927      0.162     -4.901      0.000      -1.110      -0.475
C(Management_Group)[T.Allianz]                  -0.6386      0.091     -7.007      0.000      -0.817      -0.460
C(Management_Group)[T.Allspring]             -5.674e-14   1.24e-14     -4.594      0.000    -8.1e-14   -3.25e-14
C(Management_Group)[T.Alma Capital]          -7.935e-14   2.16e-14     -3.676      0.000   -1.22e-13    -3.7e-14
C(Management_Group)[T.Alpha]                 -5.327e-15   5.69e-15     -0.936      0.349   -1.65e-14    5.84e-15
C(Management_Group)[T.Altana]                -1.422e-14   4.95e-15     -2.873      0.004   -2.39e-14   -4.51e-15
C(Management_Group)[T.Alter Domus]             4.14e-15    4.4e-15      0.942      0.347   -4.48e-15    1.28e-14
C(Management_Group)[T.Altex Asset]            2.927e-14   8.87e-15      3.300      0.001    1.19e-14    4.67e-14
C(Management_Group)[T.Altum]                    -0.8601      0.259     -3.325      0.001      -1.367      -0.353
C(Management_Group)[T.Amonis]                -8.411e-15   4.32e-15     -1.945      0.052   -1.69e-14    7.02e-17
C(Management_Group)[T.Ampega]                   -0.1776      0.174     -1.022      0.307      -0.518       0.163
C(Management_Group)[T.Amplegest]             -1.673e-14   4.48e-15     -3.735      0.000   -2.55e-14   -7.94e-15
C(Management_Group)[T.Amrego]                -9.891e-15   4.63e-15     -2.137      0.033    -1.9e-14   -8.13e-16
C(Management_Group)[T.Amundi]                   -0.8049      0.087     -9.278      0.000      -0.975      -0.635
C(Management_Group)[T.Andbank]               -1.676e-15   1.91e-15     -0.876      0.381   -5.43e-15    2.07e-15
C(Management_Group)[T.Anima]                 -1.389e-14   5.13e-15     -2.710      0.007    -2.4e-14   -3.84e-15
C(Management_Group)[T.Apex Fundrock]            -0.7205      0.097     -7.445      0.000      -0.910      -0.531
C(Management_Group)[T.Arbevel]                -2.27e-14   7.52e-15     -3.018      0.003   -3.75e-14   -7.95e-15
C(Management_Group)[T.Architas]               4.844e-15    3.8e-15      1.275      0.203   -2.61e-15    1.23e-14
C(Management_Group)[T.Arcipelagos]           -1.568e-14      6e-15     -2.615      0.009   -2.74e-14   -3.92e-15
C(Management_Group)[T.Argonaut]              -8.949e-15   4.51e-15     -1.983      0.048   -1.78e-14   -9.71e-17
C(Management_Group)[T.Arkea]                    -1.1372      0.191     -5.956      0.000      -1.512      -0.763
C(Management_Group)[T.Artemis]                   0.0241      0.215      0.112      0.911      -0.398       0.446
C(Management_Group)[T.Artisan]                -1.45e-14   4.57e-15     -3.174      0.002   -2.35e-14   -5.54e-15
C(Management_Group)[T.As]                     8.834e-15   4.61e-15      1.916      0.056   -2.08e-16    1.79e-14
C(Management_Group)[T.Ascend]                  5.51e-15   4.18e-15      1.317      0.188    -2.7e-15    1.37e-14
C(Management_Group)[T.Ascender]                  0.0063      0.356      0.018      0.986      -0.692       0.705
C(Management_Group)[T.Ashmore]                  -0.7079      0.106     -6.662      0.000      -0.916      -0.499
C(Management_Group)[T.Assenagon]             -7.526e-15   3.16e-15     -2.383      0.017   -1.37e-14   -1.33e-15
C(Management_Group)[T.Assetfi]                7.183e-15   3.36e-15      2.135      0.033    5.85e-16    1.38e-14
C(Management_Group)[T.Atlantis]                 -0.6020      0.258     -2.331      0.020      -1.109      -0.096
C(Management_Group)[T.Atomo]                 -2.341e-14   8.55e-15     -2.737      0.006   -4.02e-14   -6.63e-15
C(Management_Group)[T.Auriga]                -3.854e-15   5.72e-15     -0.674      0.500   -1.51e-14    7.36e-15
C(Management_Group)[T.Auris]                    -0.9900      0.258     -3.831      0.000      -1.497      -0.483
C(Management_Group)[T.Avaron]                -1.351e-15   2.33e-15     -0.581      0.562   -5.91e-15    3.21e-15
C(Management_Group)[T.Aviva]                    -0.6871      0.117     -5.884      0.000      -0.916      -0.458
C(Management_Group)[T.Axxion]                   -0.5493      0.174     -3.157      0.002      -0.890      -0.208
C(Management_Group)[T.Azimut]                -3.461e-15   3.53e-15     -0.981      0.327   -1.04e-14    3.46e-15
C(Management_Group)[T.BBVA]                     -1.0197      0.191     -5.351      0.000      -1.393      -0.646
C(Management_Group)[T.BCFS]                  -4.002e-15   3.88e-15     -1.032      0.302   -1.16e-14     3.6e-15
C(Management_Group)[T.BCP]                    4.628e-15   2.67e-15      1.734      0.083   -6.06e-16    9.86e-15
C(Management_Group)[T.BFT]                      -1.0402      0.356     -2.922      0.004      -1.738      -0.342
C(Management_Group)[T.BG]                    -5.038e-15   2.92e-15     -1.727      0.084   -1.08e-14    6.85e-16
C(Management_Group)[T.BI]                       -0.5054      0.154     -3.288      0.001      -0.807      -0.204
C(Management_Group)[T.BLI]                      -0.7652      0.260     -2.944      0.003      -1.275      -0.255
C(Management_Group)[T.BMO]                    7.606e-16   9.41e-16      0.808      0.419   -1.09e-15    2.61e-15
C(Management_Group)[T.BNP]                      -0.8667      0.095     -9.110      0.000      -1.053      -0.680
C(Management_Group)[T.BNY Mellon]                0.0297      0.105      0.282      0.778      -0.177       0.236
C(Management_Group)[T.BP Bertrand]            6.772e-16   2.96e-15      0.229      0.819   -5.13e-15    6.49e-15
C(Management_Group)[T.BPVI]                  -1.232e-15   2.35e-15     -0.524      0.600   -5.85e-15    3.38e-15
C(Management_Group)[T.Baillie Gifford]          -0.9176      0.162     -5.654      0.000      -1.236      -0.599
C(Management_Group)[T.Banca Lombarda]         1.475e-15   3.64e-15      0.405      0.686   -5.67e-15    8.62e-15
C(Management_Group)[T.Banco Com Port]          2.86e-15   3.43e-15      0.835      0.404   -3.86e-15    9.58e-15
C(Management_Group)[T.Bank Medici]            1.268e-16   4.17e-15      0.030      0.976   -8.06e-15    8.31e-15
C(Management_Group)[T.Bank Muscat]            2.141e-15   2.35e-15      0.911      0.362   -2.47e-15    6.75e-15
C(Management_Group)[T.Bank of Ireland]        4.706e-16   2.47e-15      0.190      0.849   -4.38e-15    5.32e-15
C(Management_Group)[T.Bantleon]                 -0.2027      0.110     -1.843      0.065      -0.418       0.013
C(Management_Group)[T.Barclays]                  0.0968      0.258      0.376      0.707      -0.409       0.602
C(Management_Group)[T.Baring]                   -0.9043      0.216     -4.190      0.000      -1.328      -0.481
C(Management_Group)[T.Baron]                  6.264e-15   3.66e-15      1.710      0.087   -9.21e-16    1.34e-14
C(Management_Group)[T.Bayerninvest]             -0.0812      0.193     -0.420      0.675      -0.461       0.298
C(Management_Group)[T.Berenberg]              6.785e-15   2.75e-15      2.465      0.014    1.39e-15    1.22e-14
C(Management_Group)[T.Blackrock]                -0.2473      0.092     -2.679      0.007      -0.428      -0.066
C(Management_Group)[T.Blackstone]               -1.0137      0.174     -5.838      0.000      -1.354      -0.673
C(Management_Group)[T.BlueBay]                  -0.9437      0.216     -4.373      0.000      -1.367      -0.520
C(Management_Group)[T.Boussard Gavaud]       -3.405e-15   3.18e-15     -1.072      0.284   -9.63e-15    2.82e-15
C(Management_Group)[T.Brandeaux]              2.724e-15   1.86e-15      1.466      0.143    -9.2e-16    6.37e-15
C(Management_Group)[T.Brevan Howard]          3.495e-15   2.43e-15      1.436      0.151   -1.28e-15    8.27e-15
C(Management_Group)[T.Brookfield]               -0.7878      0.367     -2.147      0.032      -1.507      -0.068
C(Management_Group)[T.Brown]                    -0.5044      0.174     -2.891      0.004      -0.847      -0.162
C(Management_Group)[T.C&M ]                  -8.252e-15   3.61e-15     -2.284      0.022   -1.53e-14   -1.17e-15
C(Management_Group)[T.C-Quadrat]              1.738e-15   2.67e-15      0.651      0.515    -3.5e-15    6.98e-15
C(Management_Group)[T.CAF]                    1.534e-15   2.04e-15      0.752      0.452   -2.47e-15    5.54e-15
C(Management_Group)[T.CFP]                      -0.0954      0.356     -0.268      0.789      -0.794       0.603
C(Management_Group)[T.CGAM]                     -0.0101      0.356     -0.028      0.977      -0.708       0.688
C(Management_Group)[T.CI]                       -0.8699      0.162     -5.361      0.000      -1.188      -0.552
C(Management_Group)[T.CIMC]                   1.982e-15   3.61e-15      0.549      0.583    -5.1e-15    9.07e-15
C(Management_Group)[T.CPR]                      -0.9193      0.356     -2.581      0.010      -1.618      -0.221
C(Management_Group)[T.CR]                    -5.859e-15    3.6e-15     -1.626      0.104   -1.29e-14    1.21e-15
C(Management_Group)[T.CS]                     2.313e-15   1.28e-15      1.802      0.072   -2.05e-16    4.83e-15
C(Management_Group)[T.CSAM]                  -7.865e-15   3.34e-15     -2.352      0.019   -1.44e-14   -1.31e-15
C(Management_Group)[T.Ca Indosuez]              -0.8784      0.144     -6.105      0.000      -1.161      -0.596
C(Management_Group)[T.Caam]                   6.275e-15   2.77e-15      2.264      0.024    8.39e-16    1.17e-14
C(Management_Group)[T.Cadelux]                  -0.7824      0.357     -2.189      0.029      -1.484      -0.081
C(Management_Group)[T.Caixabank]                -0.9847      0.215     -4.577      0.000      -1.407      -0.563
C(Management_Group)[T.Calamos]                   0.0082      0.191      0.043      0.966      -0.367       0.384
C(Management_Group)[T.CamGestion]             5.251e-16   1.94e-15      0.270      0.787   -3.28e-15    4.33e-15
C(Management_Group)[T.Candriam]                 -0.8472      0.109     -7.775      0.000      -1.061      -0.633
C(Management_Group)[T.Cantor]                 9.135e-15   3.18e-15      2.875      0.004     2.9e-15    1.54e-14
C(Management_Group)[T.Capital Fund]           -1.48e-14   5.16e-15     -2.865      0.004   -2.49e-14   -4.67e-15
C(Management_Group)[T.Carne]                    -0.7841      0.093     -8.393      0.000      -0.967      -0.601
C(Management_Group)[T.Carnegie]               5.439e-16   1.56e-15      0.349      0.727   -2.51e-15     3.6e-15
C(Management_Group)[T.Casa4Funds]             2.085e-15   1.93e-15      1.079      0.281   -1.71e-15    5.87e-15
C(Management_Group)[T.Castlestone]            1.622e-15    1.6e-15      1.012      0.312   -1.52e-15    4.77e-15
C(Management_Group)[T.Catalunyacaixa]         4.223e-15   1.87e-15      2.254      0.024    5.48e-16     7.9e-15
C(Management_Group)[T.Cbnk]                    5.78e-16    2.9e-15      0.199      0.842   -5.11e-15    6.26e-15
C(Management_Group)[T.Celsius]                 3.81e-15   1.59e-15      2.403      0.016       7e-16    6.92e-15
C(Management_Group)[T.Cheyne]                   -0.9235      0.356     -2.596      0.010      -1.621      -0.226
C(Management_Group)[T.Chikara]                  -0.0720      0.356     -0.202      0.840      -0.771       0.627
C(Management_Group)[T.Cholet Dupont]          2.198e-15   1.23e-15      1.789      0.074   -2.12e-16    4.61e-15
C(Management_Group)[T.Citifirst]             -1.004e-15   2.18e-15     -0.461      0.645   -5.27e-15    3.26e-15
C(Management_Group)[T.Clearbridge]           -1.861e-15   1.87e-15     -0.997      0.319   -5.52e-15     1.8e-15
C(Management_Group)[T.Close Finsbury]        -1.583e-15    2.2e-15     -0.720      0.472   -5.89e-15    2.73e-15
C(Management_Group)[T.Cohen & Steers]         1.531e-15   1.54e-15      0.994      0.321   -1.49e-15    4.55e-15
C(Management_Group)[T.Colchester]               -0.9448      0.140     -6.750      0.000      -1.219      -0.670
C(Management_Group)[T.Columbia Threadneedle]    -0.0766      0.131     -0.584      0.560      -0.334       0.181
C(Management_Group)[T.Colville]              -1.694e-15   1.38e-15     -1.230      0.219    -4.4e-15    1.01e-15
C(Management_Group)[T.Comeragh]                 -0.8685      0.366     -2.375      0.018      -1.586      -0.151
C(Management_Group)[T.Comgest]                  -0.9499      0.216     -4.404      0.000      -1.373      -0.527
C(Management_Group)[T.Cominvest]             -1.297e-15   2.92e-15     -0.445      0.657   -7.02e-15    4.42e-15
C(Management_Group)[T.Concept ]              -3.081e-16   2.15e-15     -0.143      0.886   -4.53e-15    3.92e-15
C(Management_Group)[T.Conventum]             -7.704e-16   1.41e-15     -0.546      0.585   -3.54e-15       2e-15
C(Management_Group)[T.Corner Banca]           3.909e-16   2.08e-15      0.188      0.851   -3.69e-15    4.47e-15
C(Management_Group)[T.Corum Butler]           4.584e-15   1.59e-15      2.882      0.004    1.46e-15     7.7e-15
C(Management_Group)[T.Credi-Invest]          -1.659e-15    1.6e-15     -1.036      0.300    -4.8e-15    1.48e-15
C(Management_Group)[T.Credit Andorra]        -1.434e-15   3.21e-15     -0.447      0.655   -7.72e-15    4.85e-15
C(Management_Group)[T.Credit Mutuel]         -6.855e-16   2.98e-15     -0.230      0.818   -6.53e-15    5.16e-15
C(Management_Group)[T.Credit Suisse]            -0.9539      0.358     -2.666      0.008      -1.656      -0.252
C(Management_Group)[T.Credito Agricola]       1.888e-15   1.08e-15      1.747      0.081   -2.32e-16    4.01e-15
C(Management_Group)[T.Cullen]                -3.394e-16   1.07e-15     -0.319      0.750   -2.43e-15    1.75e-15
C(Management_Group)[T.Cygnus]                 1.717e-16   2.25e-15      0.076      0.939   -4.25e-15    4.59e-15
C(Management_Group)[T.DIAM]                     -0.6215      0.258     -2.407      0.016      -1.128      -0.115
C(Management_Group)[T.DJE]                       0.0183      0.215      0.085      0.932      -0.404       0.441
C(Management_Group)[T.DNB]                      -1.0349      0.258     -4.013      0.000      -1.541      -0.529
C(Management_Group)[T.DNCA]                     -0.9826      0.215     -4.563      0.000      -1.405      -0.560
C(Management_Group)[T.DWS]                      -0.0299      0.215     -0.139      0.890      -0.452       0.392
C(Management_Group)[T.Dalton]                 2.661e-15   2.45e-15      1.088      0.277   -2.14e-15    7.46e-15
C(Management_Group)[T.Danske]                   -1.2053      0.175     -6.883      0.000      -1.549      -0.862
C(Management_Group)[T.Deka]                  -5.727e-15   2.43e-15     -2.353      0.019   -1.05e-14   -9.53e-16
C(Management_Group)[T.Delaware]              -2.599e-15   2.02e-15     -1.288      0.198   -6.56e-15    1.36e-15
C(Management_Group)[T.Delta Lloyd]            1.746e-15   1.38e-15      1.263      0.207   -9.65e-16    4.46e-15
C(Management_Group)[T.Deutsche]              -1.832e-15   2.49e-15     -0.735      0.462   -6.72e-15    3.06e-15
C(Management_Group)[T.Dodge & Cox]              -1.0427      0.356     -2.929      0.003      -1.741      -0.344
C(Management_Group)[T.Dunas]                  -8.69e-16   2.52e-15     -0.345      0.730    -5.8e-15    4.07e-15
C(Management_Group)[T.Dynasty]                1.626e-15   1.69e-15      0.964      0.335   -1.68e-15    4.93e-15
C(Management_Group)[T.EGI]                    4.354e-16   1.23e-15      0.353      0.724   -1.99e-15    2.86e-15
C(Management_Group)[T.EII]                      -1.0156      0.356     -2.853      0.004      -1.714      -0.317
C(Management_Group)[T.Eastspring]               -1.0118      0.356     -2.842      0.005      -1.710      -0.314
C(Management_Group)[T.Eaton Vance]              -1.0102      0.356     -2.837      0.005      -1.709      -0.312
C(Management_Group)[T.Ecofi]                    -1.0353      0.191     -5.428      0.000      -1.409      -0.661
C(Management_Group)[T.EdenTree]                  0.1395      0.216      0.647      0.517      -0.283       0.562
C(Management_Group)[T.Edinburgh]             -8.562e-16      2e-15     -0.428      0.669   -4.78e-15    3.07e-15

Table 5. Retail Targeting, Asset Class Interaction, and Management Effects

Without FE

In [83]:
df['Management_Group_clean'] = df['Management_Group'].fillna('Missing').astype(str)

In [84]:
import statsmodels.formula.api as smf

# 1. Required variables ONLY
vars_t5 = [
    'dividend',
    'retail_eligible_i',
    'is_fixed_income',
    'Management_Group_clean'
]

# 2. ONE SAMPLE FOR EVERYTHING
df_t5 = df[vars_t5].dropna()

# 3. Model
model_t5 = smf.ols(
    formula="dividend ~ retail_eligible_i * is_fixed_income",
    data=df_t5
).fit(
    cov_type='cluster',
    cov_kwds={'groups': df_t5['Management_Group_clean']}
)

print(model_t5.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               dividend   R-squared:                       0.038
Model:                            OLS   Adj. R-squared:                  0.036
Method:                 Least Squares   F-statistic:                     14.93
Date:                Mon, 04 May 2026   Prob (F-statistic):           5.50e-09
Time:                        06:52:06   Log-Likelihood:                -1325.5
No. Observations:                1968   AIC:                             2659.
Df Residuals:                    1964   BIC:                             2681.
Df Model:                           3
Covariance Type:              cluster
=====================================================================================================
                                        coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
Intercept                             0.1100      0.029      3.840      0.000       0.054       0.166
retail_eligible_i                     0.2981      0.047      6.402      0.000       0.207       0.389
is_fixed_income                       0.1329      0.054      2.463      0.014       0.027       0.239
retail_eligible_i:is_fixed_income    -0.1271      0.077     -1.642      0.101      -0.279       0.025
==============================================================================
Omnibus:                     9329.859   Durbin-Watson:                   1.481
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              298.093
Skew:                           0.456   Prob(JB):                     1.86e-65
Kurtosis:                       1.326   Cond. No.                         13.1
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

With FE

In [85]:
import statsmodels.formula.api as smf

# 1. Cleaned cluster variable
df['Management_Group_clean'] = df['Management_Group'].astype('category').cat.codes

# 2. Required variables
vars_t5 = [
    'dividend',
    'retail_eligible_i',
    'is_fixed_income',
    'Management_Group',
    'Management_Group_clean'
]

# 3. One size fits all
df_t5 = df[vars_t5].dropna()

# 4. Model with FE
model = smf.ols(
    formula="dividend ~ retail_eligible_i * is_fixed_income + C(Management_Group)",
    data=df_t5
).fit()

# 5. Aligned cluster
model_t5 = model.get_robustcov_results(
    cov_type='cluster',
    groups=df_t5.loc[model.model.data.row_labels, 'Management_Group_clean']
)

print(model_t5.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               dividend   R-squared:                       0.533
Model:                            OLS   Adj. R-squared:                  0.462
Method:                 Least Squares   F-statistic:                     105.2
Date:                Mon, 04 May 2026   Prob (F-statistic):           2.80e-44
Time:                        06:52:06   Log-Likelihood:                -612.62
No. Observations:                1963   AIC:                             1741.
Df Residuals:                    1705   BIC:                             3181.
Df Model:                         257
Covariance Type:              cluster
================================================================================================================
                                                   coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------
Intercept                                        0.8349      0.049     16.945      0.000       0.738       0.932
C(Management_Group)[T.ABN AMRO]                 -0.8349      0.049    -16.945      0.000      -0.932      -0.738
C(Management_Group)[T.ACATIS]                   -0.0371      0.018     -2.019      0.045      -0.073      -0.001
C(Management_Group)[T.AISM]                     -0.8349      0.049    -16.945      0.000      -0.932      -0.738
C(Management_Group)[T.AQA]                      -0.8349      0.049    -16.945      0.000      -0.932      -0.738
C(Management_Group)[T.AXA]                      -0.3780      0.001   -254.458      0.000      -0.381      -0.375
C(Management_Group)[T.Aberdeen]                 -0.2933      0.015    -19.095      0.000      -0.324      -0.263
C(Management_Group)[T.Adepa]                    -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Aegon]                    -0.8446      0.010    -81.034      0.000      -0.865      -0.824
C(Management_Group)[T.Alfred Berg]              -0.0371      0.018     -2.019      0.045      -0.073      -0.001
C(Management_Group)[T.Allfunds]                 -0.8349      0.049    -16.945      0.000      -0.932      -0.738
C(Management_Group)[T.Alliance]                 -0.8094      0.008    -96.144      0.000      -0.826      -0.793
C(Management_Group)[T.Allianz]                  -0.6900      0.002   -355.459      0.000      -0.694      -0.686
C(Management_Group)[T.Altum]                    -0.9087      0.025    -36.374      0.000      -0.958      -0.860
C(Management_Group)[T.Ampega]                   -0.1826      0.009    -21.122      0.000      -0.200      -0.166
C(Management_Group)[T.Amundi]                   -0.8036      0.006   -128.022      0.000      -0.816      -0.791
C(Management_Group)[T.Apex Fundrock]            -0.7365      0.007    -98.614      0.000      -0.751      -0.722
C(Management_Group)[T.Arkea]                    -1.0371      0.018    -56.466      0.000      -1.073      -1.001
C(Management_Group)[T.Artemis]                   0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.Ascender]                 -0.0371      0.018     -2.019      0.045      -0.073      -0.001
C(Management_Group)[T.Ashmore]                  -0.7627      0.009    -85.915      0.000      -0.780      -0.745
C(Management_Group)[T.Atlantis]                 -0.4826      0.009    -55.832      0.000      -0.500      -0.466
C(Management_Group)[T.Auris]                    -0.9623      0.035    -27.140      0.000      -1.032      -0.892
C(Management_Group)[T.Aviva]                    -0.6881      0.049    -14.185      0.000      -0.784      -0.593
C(Management_Group)[T.Axxion]                   -0.5935      0.003   -183.103      0.000      -0.600      -0.587
C(Management_Group)[T.BBVA]                     -0.9962      0.002   -526.901      0.000      -1.000      -0.992
C(Management_Group)[T.BFT]                      -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.BI]                       -0.5135      0.025    -20.880      0.000      -0.562      -0.465
C(Management_Group)[T.BLI]                      -0.8349      0.049    -16.945      0.000      -0.932      -0.738
C(Management_Group)[T.BNP]                      -0.8894      0.005   -168.863      0.000      -0.900      -0.879
C(Management_Group)[T.BNY Mellon]                0.0038      0.002      2.019      0.045    9.33e-05       0.008
C(Management_Group)[T.Baillie Gifford]          -0.9916      0.004   -239.445      0.000      -1.000      -0.983
C(Management_Group)[T.Bantleon]                 -0.1950      0.007    -29.146      0.000      -0.208      -0.182
C(Management_Group)[T.Barclays]                  0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.Baring]                   -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Bayerninvest]             -0.1112      0.053     -2.116      0.035      -0.215      -0.008
C(Management_Group)[T.Blackrock]                -0.2413      0.006    -41.816      0.000      -0.253      -0.230
C(Management_Group)[T.Blackstone]               -1.0153      0.008   -134.249      0.000      -1.030      -1.000
C(Management_Group)[T.BlueBay]                  -1.0371      0.018    -56.466      0.000      -1.073      -1.001
C(Management_Group)[T.Brookfield]               -0.8349      0.049    -16.945      0.000      -0.932      -0.738
C(Management_Group)[T.Brown]                    -0.5854      0.014    -41.149      0.000      -0.613      -0.557
C(Management_Group)[T.CFP]                       0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.CGAM]                      0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.CI]                       -0.8159      0.009    -94.399      0.000      -0.833      -0.799
C(Management_Group)[T.CPR]                      -1.0371      0.018    -56.466      0.000      -1.073      -1.001
C(Management_Group)[T.Ca Indosuez]              -0.8349      0.049    -16.945      0.000      -0.932      -0.738
C(Management_Group)[T.Cadelux]                  -0.8349      0.049    -16.945      0.000      -0.932      -0.738
C(Management_Group)[T.Caixabank]                -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Calamos]                  -0.0371      0.018     -2.019      0.045      -0.073      -0.001
C(Management_Group)[T.Candriam]                 -0.9010      0.003   -268.214      0.000      -0.908      -0.894
C(Management_Group)[T.Carne]                    -0.8154      0.007   -125.283      0.000      -0.828      -0.803
C(Management_Group)[T.Cheyne]                   -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Chikara]                   0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.Colchester]               -1.0128      0.006   -159.198      0.000      -1.025      -1.000
C(Management_Group)[T.Columbia Threadneedle]    -0.0394      0.018     -2.218      0.027      -0.074      -0.004
C(Management_Group)[T.Comeragh]                 -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Comgest]                  -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Credit Suisse]            -0.8876      0.070    -12.711      0.000      -1.025      -0.750
C(Management_Group)[T.DIAM]                     -0.4826      0.009    -55.832      0.000      -0.500      -0.466
C(Management_Group)[T.DJE]                       0.0491      0.024      2.015      0.045       0.001       0.097
C(Management_Group)[T.DNB]                      -1.0371      0.018    -56.466      0.000      -1.073      -1.001
C(Management_Group)[T.DNCA]                     -0.9691      0.023    -41.646      0.000      -1.015      -0.923
C(Management_Group)[T.DWS]                       0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.Danske]                   -1.0262      0.013    -79.153      0.000      -1.052      -1.001
C(Management_Group)[T.Dodge & Cox]              -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.EII]                      -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Eastspring]               -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Eaton Vance]              -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Ecofi]                    -0.9861      0.018    -53.757      0.000      -1.022      -0.950
C(Management_Group)[T.EdenTree]                  0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.Edmond Rothschild]        -0.8349      0.049    -16.945      0.000      -0.932      -0.738
C(Management_Group)[T.Ellipsis]                 -0.0371      0.018     -2.019      0.045      -0.073      -0.001
C(Management_Group)[T.Epsilon]                  -0.9872      0.026    -38.699      0.000      -1.037      -0.937
C(Management_Group)[T.Equitile]                 -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Equity Trustees]           0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.Erste]                    -0.1743      0.004    -46.698      0.000      -0.182      -0.167
C(Management_Group)[T.Etoile]                   -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Eurobank ]                -0.8644      0.039    -21.916      0.000      -0.942      -0.787
C(Management_Group)[T.F&C ]                      0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.FERI]                      0.1651      0.049      3.351      0.001       0.068       0.262
C(Management_Group)[T.FIL]                      -0.5379      0.002   -217.814      0.000      -0.543      -0.533
C(Management_Group)[T.FMI]                      -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Federal Finance]          -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Federated Hermes]          0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.First Private]            -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.First Sentier]            -1.0371      0.018    -56.466      0.000      -1.073      -1.001
C(Management_Group)[T.First Trust]              -0.5098      0.005   -104.864      0.000      -0.519      -0.500
C(Management_Group)[T.Fort]                     -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Franklin Templeton]       -0.7462      0.002   -394.671      0.000      -0.750      -0.742
C(Management_Group)[T.FundPartner]              -0.9556      0.014    -69.573      0.000      -0.983      -0.929
C(Management_Group)[T.FundShare]                -1.0098      0.005   -207.710      0.000      -1.019      -1.000
C(Management_Group)[T.Fundsight]                -0.8957      0.033    -27.033      0.000      -0.961      -0.830
C(Management_Group)[T.GS&P]                     -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.GSAM]                      0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.GTFinance]                -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Gam]                      -0.1952      0.008    -23.298      0.000      -0.212      -0.179
C(Management_Group)[T.Gateway]                  -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Gerifonds]                -0.8876      0.070    -12.711      0.000      -1.025      -0.750
C(Management_Group)[T.Goldman Sachs]            -0.3562      0.023    -15.729      0.000      -0.401      -0.312
C(Management_Group)[T.Groupama]                 -0.9962      0.002   -526.901      0.000      -1.000      -0.992
C(Management_Group)[T.H2O]                      -1.0371      0.018    -56.466      0.000      -1.073      -1.001
C(Management_Group)[T.HAFS]                     -0.7262      0.033    -22.231      0.000      -0.791      -0.662
C(Management_Group)[T.HF Arode]                 -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.HIML]                     -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.HSBC]                     -0.5560      0.010    -55.834      0.000      -0.576      -0.536
C(Management_Group)[T.Hamlin]                    0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.Handelsbanken]            -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Hansainvest]              -0.0997      0.006    -17.675      0.000      -0.111      -0.089
C(Management_Group)[T.Hargreaves Lansdown]       0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.Harrington]                0.1651      0.049      3.351      0.001       0.068       0.262
C(Management_Group)[T.Helaba]                    0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.Heptagon]                 -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Hermes]                   -1.0189      0.009   -108.820      0.000      -1.037      -1.000
C(Management_Group)[T.Holberg]                  -0.0371      0.018     -2.019      0.045      -0.073      -0.001
C(Management_Group)[T.IFM]                      -0.7326      0.009    -84.757      0.000      -0.750      -0.716
C(Management_Group)[T.IFSL]                     -0.1826      0.009    -21.122      0.000      -0.200      -0.166
C(Management_Group)[T.INKA]                      0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.IPConcept Lux]            -0.4826      0.009    -55.832      0.000      -0.500      -0.466
C(Management_Group)[T.IQ]                       -0.5540      0.009    -64.096      0.000      -0.571      -0.537
C(Management_Group)[T.Insight]                  -0.6745      0.014    -49.597      0.000      -0.701      -0.648
C(Management_Group)[T.JOHCM]                     0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.JP Morgan]                -0.1113      0.004    -25.750      0.000      -0.120      -0.103
C(Management_Group)[T.JSS]                      -0.6376      0.070     -9.131      0.000      -0.775      -0.500
C(Management_Group)[T.Janus]                    -0.1577      0.000  -1386.395      0.000      -0.158      -0.157
C(Management_Group)[T.Jupiter]                  -0.9909      0.004   -220.813      0.000      -1.000      -0.982
C(Management_Group)[T.Jyske]                    -0.0371      0.018     -2.019      0.045      -0.073      -0.001
C(Management_Group)[T.KBA]                      -0.7141      0.010    -73.465      0.000      -0.733      -0.695
C(Management_Group)[T.KBI]                      -0.8349      0.049    -16.945      0.000      -0.932      -0.738
C(Management_Group)[T.Kairos]                   -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Kepler]                   -0.3522      0.009    -37.619      0.000      -0.371      -0.334
C(Management_Group)[T.LBBW]                     -0.0189      0.009     -2.019      0.045      -0.037      -0.000
C(Management_Group)[T.LBO]                      -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.LBP]                      -1.0098      0.005   -207.710      0.000      -1.019      -1.000
C(Management_Group)[T.LFAM]                     -1.0371      0.018    -56.466      0.000      -1.073      -1.001
C(Management_Group)[T.LFP]                       0.0084      0.004      2.019      0.045       0.000       0.017
C(Management_Group)[T.LGIM]                     -0.9383      0.010    -93.371      0.000      -0.958      -0.918
C(Management_Group)[T.LGT]                      -0.9487      0.018    -51.392      0.000      -0.985      -0.912
C(Management_Group)[T.LLB]                      -0.1583      0.004    -38.225      0.000      -0.166      -0.150
C(Management_Group)[T.La Financiere De]         -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.La Francaise]             -0.9623      0.035    -27.140      0.000      -1.032      -0.892
C(Management_Group)[T.Lazard]                   -0.6105      0.002   -253.322      0.000      -0.615      -0.606
C(Management_Group)[T.Legal & General]           0.0118      0.006      2.019      0.045       0.000       0.023
C(Management_Group)[T.Limestone Platfo]         -0.8349      0.049    -16.945      0.000      -0.932      -0.738
C(Management_Group)[T.Link]                     -0.2761      0.005    -57.698      0.000      -0.285      -0.267
C(Management_Group)[T.Liontrust]                -0.4826      0.009    -55.832      0.000      -0.500      -0.466
C(Management_Group)[T.Lombard Odier]            -0.7598      0.005   -156.287      0.000      -0.769      -0.750
C(Management_Group)[T.Longchamp]                -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Longleaf]                 -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Lord Abbett]              -1.0371      0.018    -56.466      0.000      -1.073      -1.001
C(Management_Group)[T.Lupus alpha]               0.0174      0.009      2.019      0.045       0.000       0.034
C(Management_Group)[T.Lyxor]                    -0.8001      0.014    -56.667      0.000      -0.828      -0.772
C(Management_Group)[T.M & G ]                   -0.4323      0.006    -77.579      0.000      -0.443      -0.421
C(Management_Group)[T.MAM]                      -0.4826      0.009    -55.832      0.000      -0.500      -0.466
C(Management_Group)[T.MFS]                      -0.8349      0.049    -16.945      0.000      -0.932      -0.738
C(Management_Group)[T.MLC]                      -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.MONCEAU]                  -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Majedie]                  -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Man]                      -0.9129      0.002   -482.824      0.000      -0.917      -0.909
C(Management_Group)[T.Mandatum]                 -0.8349      0.049    -16.945      0.000      -0.932      -0.738
C(Management_Group)[T.Manulife]                 -1.0371      0.018    -56.466      0.000      -1.073      -1.001
C(Management_Group)[T.Maple-Brown Abbott]       -0.9826      0.009   -113.682      0.000      -1.000      -0.966
C(Management_Group)[T.Masterinvest]             -0.0371      0.018     -2.019      0.045      -0.073      -0.001
C(Management_Group)[T.Mercer]                   -0.9431      0.000  -3443.305      0.000      -0.944      -0.943
C(Management_Group)[T.Method]                   -0.8349      0.049    -16.945      0.000      -0.932      -0.738
C(Management_Group)[T.Montlake]                 -0.6492      0.009    -75.115      0.000      -0.666      -0.632
C(Management_Group)[T.Morgan Stanley]           -0.3159      0.009    -36.548      0.000      -0.333      -0.299
C(Management_Group)[T.Multiconcept]             -0.8506      0.020    -42.166      0.000      -0.890      -0.811

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 257, but rank is 3
  warnings.warn('covariance of constraints does not have full '

Table 6. Retail Targeting vs Economic Accessibility.

Without FE

In [86]:
vars_t6 = [
    'dividend',
    'retail_eligible_i',
    'log_min_inv',
    'Management_Group_clean'
]

df_t6 = df[vars_t6].dropna()

model = smf.ols(
    formula="dividend ~ retail_eligible_i + log_min_inv",
    data=df_t6
).fit()

model_t6 = model.get_robustcov_results(
    cov_type='cluster',
    groups=df_t6.loc[model.model.data.row_labels, 'Management_Group_clean']
)

print(model_t6.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               dividend   R-squared:                       0.034
Model:                            OLS   Adj. R-squared:                  0.033
Method:                 Least Squares   F-statistic:                     15.70
Date:                Mon, 04 May 2026   Prob (F-statistic):           3.82e-07
Time:                        06:52:06   Log-Likelihood:                -1266.4
No. Observations:                1855   AIC:                             2539.
Df Residuals:                    1852   BIC:                             2555.
Df Model:                           2
Covariance Type:              cluster
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             0.1876      0.083      2.252      0.025       0.024       0.352
retail_eligible_i     0.2648      0.049      5.423      0.000       0.169       0.361
log_min_inv          -0.0061      0.017     -0.353      0.724      -0.040       0.028
==============================================================================
Omnibus:                     8386.408   Durbin-Watson:                   1.468
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              279.223
Skew:                           0.408   Prob(JB):                     2.33e-61
Kurtosis:                       1.283   Cond. No.                         23.3
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

With FE

In [87]:
vars_t6_fe = [
    'dividend',
    'retail_eligible_i',
    'log_min_inv',
    'Management_Group',
    'Management_Group_clean'
]

df_t6_fe = df[vars_t6_fe].dropna()

model = smf.ols(
    formula="dividend ~ retail_eligible_i + log_min_inv + C(Management_Group)",
    data=df_t6_fe
).fit()

model_t6_fe = model.get_robustcov_results(
    cov_type='cluster',
    groups=df_t6_fe.loc[model.model.data.row_labels, 'Management_Group_clean']
)

print(model_t6_fe.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               dividend   R-squared:                       0.542
Model:                            OLS   Adj. R-squared:                  0.471
Method:                 Least Squares   F-statistic:                     58.09
Date:                Mon, 04 May 2026   Prob (F-statistic):           2.17e-21
Time:                        06:52:06   Log-Likelihood:                -573.71
No. Observations:                1853   AIC:                             1645.
Df Residuals:                    1604   BIC:                             3021.
Df Model:                         248
Covariance Type:              cluster
================================================================================================================
                                                   coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------
Intercept                                        0.8729      0.060     14.568      0.000       0.755       0.991
C(Management_Group)[T.ABN AMRO]                 -0.7540      0.085     -8.838      0.000      -0.922      -0.586
C(Management_Group)[T.ACATIS]                   -0.0281      0.019     -1.496      0.136      -0.065       0.009
C(Management_Group)[T.AISM]                     -0.7798      0.074    -10.606      0.000      -0.925      -0.635
C(Management_Group)[T.AQA]                      -0.7877      0.070    -11.194      0.000      -0.926      -0.649
C(Management_Group)[T.AXA]                      -0.2888      0.058     -5.009      0.000      -0.402      -0.175
C(Management_Group)[T.Aberdeen]                 -0.1899      0.067     -2.827      0.005      -0.322      -0.058
C(Management_Group)[T.Adepa]                    -1.0281      0.019    -54.663      0.000      -1.065      -0.991
C(Management_Group)[T.Aegon]                    -0.7312      0.062    -11.839      0.000      -0.853      -0.610
C(Management_Group)[T.Alfred Berg]               0.1274      0.085      1.496      0.136      -0.040       0.295
C(Management_Group)[T.Allfunds]                 -0.7263      0.100     -7.280      0.000      -0.923      -0.530
C(Management_Group)[T.Alliance]                 -0.6947      0.076     -9.094      0.000      -0.845      -0.544
C(Management_Group)[T.Allianz]                  -0.5983      0.064     -9.379      0.000      -0.724      -0.473
C(Management_Group)[T.Altum]                    -0.8475      0.059    -14.428      0.000      -0.963      -0.732
C(Management_Group)[T.Ampega]                   -0.1568      0.029     -5.429      0.000      -0.214      -0.100
C(Management_Group)[T.Amundi]                   -0.7282      0.043    -17.100      0.000      -0.812      -0.644
C(Management_Group)[T.Apex Fundrock]            -0.6437      0.050    -12.927      0.000      -0.742      -0.546
C(Management_Group)[T.Arkea]                    -0.9167      0.056    -16.455      0.000      -1.026      -0.807
C(Management_Group)[T.Artemis]                   0.0788      0.053      1.496      0.136      -0.025       0.183
C(Management_Group)[T.Ascender]                  0.1165      0.078      1.496      0.136      -0.037       0.270
C(Management_Group)[T.Ashmore]                  -0.6528      0.061    -10.733      0.000      -0.773      -0.533
C(Management_Group)[T.Atlantis]                 -0.4251      0.050     -8.492      0.000      -0.524      -0.327
C(Management_Group)[T.Auris]                    -0.8941      0.035    -25.470      0.000      -0.963      -0.825
C(Management_Group)[T.Aviva]                    -0.6080      0.080     -7.636      0.000      -0.765      -0.451
C(Management_Group)[T.Axxion]                   -0.5552      0.030    -18.547      0.000      -0.614      -0.496
C(Management_Group)[T.BBVA]                     -0.8871      0.076    -11.749      0.000      -1.036      -0.738
C(Management_Group)[T.BFT]                      -1.0281      0.019    -54.663      0.000      -1.065      -0.991
C(Management_Group)[T.BI]                       -0.4609      0.039    -11.776      0.000      -0.538      -0.384
C(Management_Group)[T.BNP]                      -0.7959      0.047    -16.828      0.000      -0.889      -0.703
C(Management_Group)[T.BNY Mellon]                0.1049      0.070      1.496      0.136      -0.033       0.243
C(Management_Group)[T.Baillie Gifford]          -0.9026      0.065    -13.867      0.000      -1.031      -0.774
C(Management_Group)[T.Bantleon]                 -0.1497      0.003    -49.346      0.000      -0.156      -0.144
C(Management_Group)[T.Barclays]                  0.0977      0.065      1.496      0.136      -0.031       0.226
C(Management_Group)[T.Baring]                   -0.9595      0.027    -35.396      0.000      -1.013      -0.906
C(Management_Group)[T.Bayerninvest]             -0.0085      0.083     -0.102      0.919      -0.172       0.155
C(Management_Group)[T.Blackrock]                -0.1445      0.072     -2.014      0.045      -0.286      -0.003
C(Management_Group)[T.Blackstone]               -0.9065      0.063    -14.497      0.000      -1.030      -0.783
C(Management_Group)[T.BlueBay]                  -0.9320      0.045    -20.514      0.000      -1.022      -0.843
C(Management_Group)[T.Brookfield]               -0.7660      0.080     -9.621      0.000      -0.923      -0.609
C(Management_Group)[T.Brown]                    -0.4536      0.078     -5.785      0.000      -0.608      -0.299
C(Management_Group)[T.CFP]                       0.0788      0.053      1.496      0.136      -0.025       0.183
C(Management_Group)[T.CGAM]                      0.0709      0.047      1.496      0.136      -0.022       0.164
C(Management_Group)[T.CI]                       -0.8228      0.007   -117.187      0.000      -0.837      -0.809
C(Management_Group)[T.CPR]                      -0.9291      0.047    -19.589      0.000      -1.022      -0.836
C(Management_Group)[T.Ca Indosuez]              -0.7712      0.077     -9.986      0.000      -0.923      -0.619
C(Management_Group)[T.Cadelux]                  -0.8333      0.058    -14.257      0.000      -0.948      -0.718
C(Management_Group)[T.Caixabank]                -0.9172      0.055    -16.568      0.000      -1.026      -0.808
C(Management_Group)[T.Calamos]                   0.1046      0.070      1.496      0.136      -0.033       0.242
C(Management_Group)[T.Candriam]                 -0.8916      0.014    -63.808      0.000      -0.919      -0.864
C(Management_Group)[T.Carne]                    -0.7477      0.053    -14.082      0.000      -0.852      -0.643
C(Management_Group)[T.Cheyne]                   -0.8756      0.083    -10.526      0.000      -1.039      -0.712
C(Management_Group)[T.Chikara]                   0.0709      0.047      1.496      0.136      -0.022       0.164
C(Management_Group)[T.Colchester]               -0.8998      0.067    -13.431      0.000      -1.032      -0.768
C(Management_Group)[T.Columbia Threadneedle]     0.0496      0.061      0.816      0.415      -0.070       0.169
C(Management_Group)[T.Comeragh]                 -0.9291      0.047    -19.589      0.000      -1.022      -0.836
C(Management_Group)[T.Comgest]                  -0.9117      0.059    -15.448      0.000      -1.028      -0.795
C(Management_Group)[T.Credit Suisse]            -0.8729      0.060    -14.568      0.000      -0.991      -0.755
C(Management_Group)[T.DIAM]                     -0.3998      0.067     -5.967      0.000      -0.532      -0.268
C(Management_Group)[T.DJE]                       0.1311      0.057      2.295      0.023       0.019       0.244
C(Management_Group)[T.DNB]                      -0.8756      0.083    -10.526      0.000      -1.039      -0.712
C(Management_Group)[T.DNCA]                     -0.9084      0.033    -27.128      0.000      -0.974      -0.842
C(Management_Group)[T.DWS]                       0.0479      0.032      1.496      0.136      -0.015       0.111
C(Management_Group)[T.Danske]                   -0.9268      0.049    -18.934      0.000      -1.023      -0.830
C(Management_Group)[T.Dodge & Cox]              -0.9291      0.047    -19.589      0.000      -1.022      -0.836
C(Management_Group)[T.EII]                      -0.9093      0.061    -14.985      0.000      -1.029      -0.790
C(Management_Group)[T.Eastspring]               -0.9212      0.053    -17.480      0.000      -1.025      -0.817
C(Management_Group)[T.Eaton Vance]              -0.8954      0.070    -12.803      0.000      -1.033      -0.758
C(Management_Group)[T.Ecofi]                    -0.9893      0.023    -42.571      0.000      -1.035      -0.944
C(Management_Group)[T.EdenTree]                  0.0907      0.061      1.496      0.136      -0.029       0.210
C(Management_Group)[T.Ellipsis]                  0.0115      0.008      1.496      0.136      -0.004       0.027
C(Management_Group)[T.Epsilon]                  -0.9229      0.026    -35.343      0.000      -0.974      -0.871
C(Management_Group)[T.Equitile]                 -0.9489      0.034    -27.760      0.000      -1.016      -0.882
C(Management_Group)[T.Equity Trustees]           0.1046      0.070      1.496      0.136      -0.033       0.242
C(Management_Group)[T.Erste]                    -0.1905      0.006    -32.806      0.000      -0.202      -0.179
C(Management_Group)[T.Etoile]                   -1.0281      0.019    -54.663      0.000      -1.065      -0.991
C(Management_Group)[T.Eurobank ]                -0.9040      0.049    -18.407      0.000      -1.001      -0.807
C(Management_Group)[T.F&C ]                      0.0511      0.034      1.496      0.136      -0.016       0.118
C(Management_Group)[T.FERI]                      0.2460      0.085      2.883      0.004       0.078       0.414
C(Management_Group)[T.FIL]                      -0.4514      0.061     -7.379      0.000      -0.572      -0.331
C(Management_Group)[T.FMI]                      -0.9687      0.021    -46.275      0.000      -1.010      -0.927
C(Management_Group)[T.Federal Finance]          -0.9230      0.051    -17.925      0.000      -1.024      -0.822
C(Management_Group)[T.Federated Hermes]          0.1123      0.075      1.496      0.136      -0.036       0.260
C(Management_Group)[T.First Private]            -0.9086      0.061    -14.870      0.000      -1.029      -0.788
C(Management_Group)[T.First Sentier]            -0.9152      0.057    -16.145      0.000      -1.027      -0.804
C(Management_Group)[T.First Trust]              -0.3894      0.074     -5.268      0.000      -0.535      -0.244
C(Management_Group)[T.Fort]                     -0.9093      0.061    -14.985      0.000      -1.029      -0.790
C(Management_Group)[T.Franklin Templeton]       -0.6564      0.063    -10.490      0.000      -0.780      -0.533
C(Management_Group)[T.FundPartner]              -0.8992      0.044    -20.261      0.000      -0.987      -0.812
C(Management_Group)[T.FundShare]                -1.0281      0.019    -54.663      0.000      -1.065      -0.991
C(Management_Group)[T.Fundsight]                -0.8038      0.074    -10.831      0.000      -0.950      -0.658
C(Management_Group)[T.GS&P]                     -0.9291      0.047    -19.589      0.000      -1.022      -0.836
C(Management_Group)[T.GSAM]                      0.0907      0.061      1.496      0.136      -0.029       0.210
C(Management_Group)[T.GTFinance]                -1.0281      0.019    -54.663      0.000      -1.065      -0.991
C(Management_Group)[T.Gam]                      -0.1222      0.042     -2.933      0.004      -0.204      -0.040
C(Management_Group)[T.Gateway]                  -0.8924      0.072    -12.407      0.000      -1.034      -0.751
C(Management_Group)[T.Gerifonds]                -0.8729      0.060    -14.568      0.000      -0.991      -0.755
C(Management_Group)[T.Goldman Sachs]            -0.2507      0.064     -3.948      0.000      -0.376      -0.126
C(Management_Group)[T.Groupama]                 -1.0281      0.019    -54.663      0.000      -1.065      -0.991
C(Management_Group)[T.H2O]                      -0.9291      0.047    -19.589      0.000      -1.022      -0.836
C(Management_Group)[T.HAFS]                     -0.6309      0.078     -8.110      0.000      -0.784      -0.478
C(Management_Group)[T.HF Arode]                 -0.9291      0.047    -19.589      0.000      -1.022      -0.836
C(Management_Group)[T.HIML]                     -0.9291      0.047    -19.589      0.000      -1.022      -0.836
C(Management_Group)[T.HSBC]                     -0.4497      0.067     -6.676      0.000      -0.582      -0.317
C(Management_Group)[T.Hamlin]                    0.0907      0.061      1.496      0.136      -0.029       0.210
C(Management_Group)[T.Handelsbanken]            -1.0281      0.019    -54.663      0.000      -1.065      -0.991
C(Management_Group)[T.Hansainvest]              -0.0845      0.018     -4.745      0.000      -0.120      -0.049
C(Management_Group)[T.Hargreaves Lansdown]       0.0744      0.050      1.496      0.136      -0.024       0.172
C(Management_Group)[T.Harrington]                0.1469      0.058      2.547      0.011       0.033       0.261
C(Management_Group)[T.Helaba]                   -0.0281      0.019     -1.496      0.136      -0.065       0.009
C(Management_Group)[T.Heptagon]                 -0.8696      0.087     -9.976      0.000      -1.041      -0.698
C(Management_Group)[T.Hermes]                   -0.9330      0.045    -20.841      0.000      -1.021      -0.845
C(Management_Group)[T.Holberg]                   0.1106      0.074      1.496      0.136      -0.035       0.256
C(Management_Group)[T.IFM]                      -0.6766      0.049    -13.790      0.000      -0.773      -0.580
C(Management_Group)[T.IFSL]                     -0.1568      0.029     -5.429      0.000      -0.214      -0.100
C(Management_Group)[T.INKA]                      0.0709      0.047      1.496      0.136      -0.022       0.164
C(Management_Group)[T.IPConcept Lux]            -0.3857      0.010    -40.441      0.000      -0.405      -0.367
C(Management_Group)[T.IQ]                       -0.4773      0.063     -7.584      0.000      -0.601      -0.353
C(Management_Group)[T.Insight]                  -0.5735      0.049    -11.656      0.000      -0.670      -0.477
C(Management_Group)[T.JOHCM]                     0.0313      0.021      1.496      0.136      -0.010       0.073
C(Management_Group)[T.JP Morgan]                 0.0163      0.067      0.245      0.807      -0.115       0.148
C(Management_Group)[T.JSS]                      -0.6229      0.060    -10.396      0.000      -0.741      -0.505
C(Management_Group)[T.Janus]                    -0.0860      0.048     -1.789      0.075      -0.181       0.009
C(Management_Group)[T.Jupiter]                  -0.9125      0.059    -15.595      0.000      -1.028      -0.797
C(Management_Group)[T.Jyske]                     0.0115      0.008      1.496      0.136      -0.004       0.027
C(Management_Group)[T.KBA]                      -0.6597      0.048    -13.671      0.000      -0.755      -0.565
C(Management_Group)[T.Kairos]                   -0.8998      0.067    -13.431      0.000      -1.032      -0.768
C(Management_Group)[T.Kepler]                   -0.2908      0.028    -10.227      0.000      -0.347      -0.235
C(Management_Group)[T.LBBW]                      0.0685      0.046      1.496      0.136      -0.022       0.159
C(Management_Group)[T.LBP]                      -0.9640      0.024    -40.009      0.000      -1.011      -0.917
C(Management_Group)[T.LFAM]                     -0.9277      0.048    -19.196      0.000      -1.023      -0.833
C(Management_Group)[T.LFP]                       0.0643      0.043      1.496      0.136      -0.020       0.149
C(Management_Group)[T.LGIM]                     -0.8206      0.074    -11.105      0.000      -0.966      -0.675
C(Management_Group)[T.LGT]                      -0.9303      0.023    -40.295      0.000      -0.976      -0.885
C(Management_Group)[T.LLB]                      -0.1086      0.039     -2.799      0.006      -0.185      -0.032
C(Management_Group)[T.La Financiere De]         -1.0281      0.019    -54.663      0.000      -1.065      -0.991
C(Management_Group)[T.La Francaise]             -0.9152      0.057    -16.145      0.000      -1.027      -0.804
C(Management_Group)[T.Lazard]                   -0.5475      0.045    -12.068      0.000      -0.637      -0.458
C(Management_Group)[T.Legal & General]           0.1026      0.069      1.496      0.136      -0.033       0.238
C(Management_Group)[T.Limestone Platfo]         -0.7738      0.076    -10.173      0.000      -0.924      -0.624
C(Management_Group)[T.Link]                     -0.1905      0.064     -2.993      0.003      -0.316      -0.065
C(Management_Group)[T.Liontrust]                -0.4083      0.061     -6.659      0.000      -0.529      -0.288
C(Management_Group)[T.Lombard Odier]            -0.7019      0.032    -21.806      0.000      -0.765      -0.638
C(Management_Group)[T.Longchamp]                -0.9291      0.047    -19.589      0.000      -1.022      -0.836
C(Management_Group)[T.Longleaf]                 -0.9093      0.061    -14.985      0.000      -1.029      -0.790
C(Management_Group)[T.Lord Abbett]              -0.9093      0.061    -14.985      0.000      -1.029      -0.790
C(Management_Group)[T.Lupus alpha]               0.1106      0.074      1.496      0.136      -0.035       0.256
C(Management_Group)[T.Lyxor]                    -0.7431      0.044    -16.722      0.000      -0.831      -0.656
C(Management_Group)[T.M & G ]                   -0.3332      0.059     -5.676      0.000      -0.449      -0.218
C(Management_Group)[T.MAM]                      -0.4231      0.051     -8.229      0.000      -0.524      -0.322
C(Management_Group)[T.MFS]                      -0.7474      0.089     -8.434      0.000      -0.922      -0.573
C(Management_Group)[T.MLC]                      -0.9093      0.061    -14.985      0.000      -1.029      -0.790
C(Management_Group)[T.MONCEAU]                  -0.9687      0.021    -46.275      0.000      -1.010      -0.927
C(Management_Group)[T.Majedie]                  -0.9291      0.047    -19.589      0.000      -1.022      -0.836
C(Management_Group)[T.Man]                      -0.8220      0.061    -13.496      0.000      -0.942      -0.702
C(Management_Group)[T.Mandatum]                 -0.7307      0.097     -7.504      0.000      -0.923      -0.539
C(Management_Group)[T.Manulife]                 -0.9192      0.054    -17.005      0.000      -1.026      -0.813
C(Management_Group)[T.Maple-Brown Abbott]       -0.9093      0.061    -14.985      0.000      -1.029      -0.790
C(Management_Group)[T.Masterinvest]              0.0511      0.034      1.496      0.136      -0.016       0.118
C(Management_Group)[T.Mercer]                   -0.9701      0.018    -54.843      0.000      -1.005      -0.935
C(Management_Group)[T.Method]                   -0.8729      0.060    -14.568      0.000      -0.991      -0.755
C(Management_Group)[T.Montlake]                 -0.5753      0.061     -9.422      0.000      -0.696      -0.455
C(Management_Group)[T.Morgan Stanley]            0.0680      0.045      1.496      0.136      -0.022       0.157
C(Management_Group)[T.Multiconcept]             -0.8005      0.035    -23.071      0.000      -0.869      -0.732
C(Management_Group)[T.Muzinich]                 -0.9053      0.063    -14.299      0.000      -1.030      -0.781
C(Management_Group)[T.NFU Mutual Unit]           0.0184      0.012      1.496      0.136      -0.006       0.043
C(Management_Group)[T.NS ]                      -0.9575      0.028    -33.671      0.000      -1.013      -0.901
C(Management_Group)[T.Natixis]                  -0.8638      0.051    -17.100      0.000      -0.963      -0.764

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 248, but rank is 2
  warnings.warn('covariance of constraints does not have full '

Table A.1 – Sample Comparison

In [88]:
df_full = pd.read_excel("ucits_dividend_data.xlsx")

vars_model = [
    'dividend_paid',
    'retail_eligible_i',
    'log_tna',
    'fund_age_years',
    'is_equity',
    'is_fixed_income'
]

df_final = df_full[vars_model].dropna()

# -----------------------------
# SAMPLE COMPARISON
# -----------------------------
vars_compare = ['log_tna', 'fund_age_years', 'is_equity', 'is_fixed_income']

summary_full = df_full[vars_compare].mean()
summary_final = df_final[vars_compare].mean()

comparison = pd.DataFrame({
    'Full sample': summary_full,
    'Final sample': summary_final,
    'Difference': summary_final - summary_full
})

print(comparison)

                 Full sample  Final sample  Difference
log_tna             3.929630      4.162036    0.232406
fund_age_years     14.159420     10.104643   -4.054777
is_equity           0.348268      0.386047    0.037779
is_fixed_income     0.299111      0.309044    0.009933

Table A.2. Alternative Measure of Economic Accessibility

In [89]:
# Subsample
vars_model = [
    'dividend_paid',
    'retail_eligible_i',
    'high_min_inv',
    'log_tna',
    'fund_age_years',
    'is_equity',
    'is_fixed_income',
    'Management_Group'
]

df_base = df[vars_model].dropna()

# Model
model_alt = smf.ols(
    "dividend_paid ~ retail_eligible_i + high_min_inv + log_tna + fund_age_years + is_equity + is_fixed_income",
    data=df_base
).fit(
    cov_type='cluster',
    cov_kwds={'groups': df_base['Management_Group']}
)

# 5. Output
print(model_alt.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          dividend_paid   R-squared:                       0.071
Model:                            OLS   Adj. R-squared:                  0.068
Method:                 Least Squares   F-statistic:                     4.198
Date:                Mon, 04 May 2026   Prob (F-statistic):           0.000479
Time:                        06:52:08   Log-Likelihood:                -859.84
No. Observations:                1930   AIC:                             1734.
Df Residuals:                    1923   BIC:                             1773.
Df Model:                           6
Covariance Type:              cluster
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             0.0441      0.042      1.057      0.290      -0.038       0.126
retail_eligible_i     0.0872      0.032      2.696      0.007       0.024       0.151
high_min_inv         -0.0686      0.044     -1.575      0.115      -0.154       0.017
log_tna              -0.0026      0.007     -0.389      0.697      -0.016       0.011
fund_age_years        0.0090      0.002      4.201      0.000       0.005       0.013
is_equity            -0.0338      0.025     -1.359      0.174      -0.082       0.015
is_fixed_income       0.1140      0.043      2.639      0.008       0.029       0.199
==============================================================================
Omnibus:                      400.201   Durbin-Watson:                   1.806
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              688.624
Skew:                           1.439   Prob(JB):                    2.93e-150
Kurtosis:                       3.533   Cond. No.                         58.3
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

Table A.3. Dividend Intensity and Retail Targeting

In [90]:
# Controls
controls = "log_tna + fund_age_years + is_equity + is_fixed_income"

vars_base = [
    'dividend_paid',
    'retail_eligible_i',
    'log_tna',
    'fund_age_years',
    'is_equity',
    'is_fixed_income',
    'Management_Group'
]

df_base = df[vars_base].dropna()

# -----------------------------
# (1) BASELINE MODEL
# -----------------------------
model1 = smf.ols(
    f"dividend_paid ~ retail_eligible_i + {controls}",
    data=df_base
).fit()

res1 = model1.get_robustcov_results(
    cov_type='cluster',
    groups=df_base.loc[model1.model.data.row_labels, 'Management_Group']
)

# -----------------------------
# (2) INTENSITY (PAYING MEMBERS ONLY)
# -----------------------------
df_paid = df_base.copy()
df_paid['log_div_value'] = df['log_div_value']

df_paid = df_paid[
    (df_paid['dividend_paid'] == 1) &
    (df_paid['log_div_value'].notnull())
]

model2 = smf.ols(
    f"log_div_value ~ retail_eligible_i + {controls}",
    data=df_paid
).fit()

res2 = model2.get_robustcov_results(
    cov_type='cluster',
    groups=df_paid.loc[model2.model.data.row_labels, 'Management_Group']
)

# Output
print("\n(1) Dividend (Baseline)")
print(res1.summary())

print("\n(2) Log Dividend Value (Paid Funds)")
print(res2.summary())

(1) Dividend (Baseline)
                            OLS Regression Results
==============================================================================
Dep. Variable:          dividend_paid   R-squared:                       0.064
Model:                            OLS   Adj. R-squared:                  0.062
Method:                 Least Squares   F-statistic:                     4.956
Date:                Mon, 04 May 2026   Prob (F-statistic):           0.000239
Time:                        06:52:09   Log-Likelihood:                -867.42
No. Observations:                1930   AIC:                             1747.
Df Residuals:                    1924   BIC:                             1780.
Df Model:                           5
Covariance Type:              cluster
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             0.0133      0.046      0.286      0.775      -0.078       0.105
retail_eligible_i     0.0811      0.030      2.666      0.008       0.021       0.141
log_tna              -0.0036      0.006     -0.569      0.570      -0.016       0.009
fund_age_years        0.0098      0.002      4.367      0.000       0.005       0.014
is_equity            -0.0350      0.024     -1.438      0.152      -0.083       0.013
is_fixed_income       0.1138      0.044      2.587      0.010       0.027       0.200
==============================================================================
Omnibus:                      404.683   Durbin-Watson:                   1.797
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              700.606
Skew:                           1.452   Prob(JB):                    7.34e-153
Kurtosis:                       3.531   Cond. No.                         57.4
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

(2) Log Dividend Value (Paid Funds)
                            OLS Regression Results
==============================================================================
Dep. Variable:          log_div_value   R-squared:                       0.032
Model:                            OLS   Adj. R-squared:                  0.016
Method:                 Least Squares   F-statistic:                    0.9998
Date:                Mon, 04 May 2026   Prob (F-statistic):              0.422
Time:                        06:52:09   Log-Likelihood:                -541.25
No. Observations:                 323   AIC:                             1094.
Df Residuals:                     317   BIC:                             1117.
Df Model:                           5
Covariance Type:              cluster
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             1.9930      0.516      3.864      0.000       0.970       3.016
retail_eligible_i    -0.1147      0.395     -0.290      0.772      -0.898       0.669
log_tna              -0.0676      0.042     -1.599      0.113      -0.151       0.016
fund_age_years       -0.0150      0.013     -1.121      0.265      -0.041       0.012
is_equity            -0.4181      0.281     -1.486      0.140      -0.976       0.140
is_fixed_income      -0.3647      0.248     -1.471      0.144      -0.856       0.127
==============================================================================
Omnibus:                      128.206   Durbin-Watson:                   1.739
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              410.247
Skew:                           1.806   Prob(JB):                     8.24e-90
Kurtosis:                       7.175   Cond. No.                         93.5
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)